prevent index name collisions
nextcloud/cms_pico pull request #186
Opened 2021-12-12 21:32 UTC by Cuchulain

Fix for bug on app enabling

2021-12-12 21:49 UTC, Cuchulain commented
Bug in Scrutinizer test definition (SSL certificate problem: certificate has expired)

2021-12-13 06:53 UTC, Cuchulain commented
With `curl -k` test passed, but not for nextcloud **master** branch.

2021-12-13 09:38 UTC, PhrozenByte commented
Thank you for your contribution :+1:

> Fix for bug on app enabling

What bug? :thinking: Unless they didn't change something I missed, indices don't have to be unique across tables.

2021-12-20 10:21 UTC, Cuchulain commented
> What bug? 🤔 Unless they didn't change something I missed, indices don't have to be unique across tables.

In last Nextcloud version pico_cms app can't be instaled, because index **user_id** already exists in NC core definitions.

2021-12-20 10:24 UTC, Cuchulain commented
> ...indices don't have to be unique across tables.

I am using PostgreSQL, where index names is unique ;-)

2021-12-20 19:33 UTC, PhrozenByte requested changes
I see, thank you for the clarification :+1: This is indeed a bug then.

It's reproducible with SQLite, too. See https://scrutinizer-ci.com/g/nextcloud/cms_pico/inspections/3b9be198-9690-4fee-97bc-5e4d36e58087

Usually we don't edit existing migrations, because migrations run only once. We rather create a new migration addressing the issue. However, the `Version010000` migration will fail as soon as it is executed (i.e. later migrations won't come into play), so we must indeed edit the `Version010000` migration.

However, we still need an additional migration to also migrate existing installs. Otherwise old installs will use the `user_id` index, whereas new installs use `cms_pico_websites_user_id`. Please add another migration to change the index for existing installs, too.

2021-12-20 21:18 UTC, PhrozenByte commented on .scrutinizer.yml
> +          - curl -k -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
I've just moved most Scrutinizer CI checks to GitHub Actions. Scrutinizer CI is now fully optional and used for analysis only. As soon as other issues occur due to their ancient software we'll remove Scrutinizer CI altogether...

2022-01-10 22:08 UTC, PhrozenByte commented
Any updates @Cuchulain?

2022-01-17 12:12 UTC, closed without merging

2022-01-17 12:55 UTC, PhrozenByte commented
Fixed in dbe2b4a

Please try cms_pico's latest version v1.0.17.